hmcts/et-xui-e2e-tests

codecept.conf.js
test/e2e/SearchCaseOnECM/scotlandSingle.js
test/pages/caselist.page.js
test/pages/judgementCollection.page.js
test/util.js

push RET-4026 changes to remote

---

test/e2e/codecept.conf.js
test/e2e/config.js
test/e2e/scenario/ETCaseSubmission-ET1Verification.js
test/pages/personalDetails.page.js

Enter personal details journey
```
[ ] Yes
[ x] No
```

Personal details section

---

test/e2e/codecept.conf.js
test/e2e/scenario/ETCaseSubmission-ET1Verification.js
test/pages/employmentAndRespondentDetails.page.js

Update e2e journey to include employment and respondent details for the still working scenario
```
[ ] Yes
[x] No
```

add the still working journey to the e2e test

---

test/e2e/codecept.conf.js
test/e2e/scenario/ETCaseSubmission-ET1Verification.js
test/pages/claimDetail.page.js
test/pages/submitClaim.page.js

Claim details steps and submission
```
[ ] Yes
[x] No
```

add claim details and submission steps

---

Jenkinsfile_nightly

Ret 2718 pj

---

test/e2e/config.js

ensure browser config set to false so tests are run in headless mode
```
[ ] Yes
[x] No
```

remove show browser so tests run in headless mode

---

Jenkinsfile_nightly

enable fortify scan

---

Jenkinsfile_nightly
package.json
security.sh

Enable fortify sacn

---

Jenkinsfile_nightly
test/e2e/scenario/ETCaseSubmission-AreYouStillWorkingForOrg.js
test/pages/citizenhub.pages.js

RET-2261_automation

---

Jenkinsfile_nightly
test/e2e/config.js

Create jenkins parameters to enable running the test against different environment including preview environments
```
[ ] Yes
[ X] No
```

Test out jenkins params

---

test/e2e/scenario/SendNotification-LegalRep.js
test/pages/applicationsTabs.pages.js
test/pages/caselist.page.js
test/pages/sendNotification.pages.js

https://tools.hmcts.net/jira/browse/RET-3809)
```
[ ] Yes
[x] No
```

RET-3809 - Send Notification - Tribunal - Request - Legal Rep Respond

---

test/pages/caselist.page.js
test/pages/login.page.js
test/pages/submitClaim.page.js

Reduced explicit wait times

---

test/e2e/scenario/ET3-Notification.js
test/e2e/scenario/ETCaseSubmission-DidNotWorkForOrg.js
test/e2e/scenario/EtLegalRep-CaseProgression.js
test/e2e/scenario/SendNotification-Caseworker.js
test/e2e/scenario/SendNotification-LegalRep.js
test/pages/applicationsTabs.pages.js
test/pages/citizenhub.pages.js
test/pages/employmentAndRespondentDetails.page.js
test/pages/et3Notification.pages.js
test/pages/respondentRepresentative.pages.js

fix failing test

---

renovate.json

Fixed renovate config
```
[ ] Yes
[x] No
```

Renovate config fix

---

Jenkinsfile_nightly

change cron job time

---

codecept.conf.js
test/e2e/scenario/ET1ClaimantLegalRep.js
test/e2e/scenario/ET1LegalRep.js
test/helper/postcode.js
test/pages/caselist.page.js
test/pages/et1CreateDraftClaim.js

et1 legal rep test

---

package.json

fix CI report

---

package.json
playwright.config.ts
playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/et1CaseServingPage.ts

Sync nightly fix ci

---

package.json
playwrighte2e/helper/accessibilityHelper.ts
playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/citizenHubPage.ts
playwrighte2e/pages/createCaseThroughApi.ts
playwrighte2e/pages/et1CaseServingPage.ts
playwrighte2e/pages/et3LoginPage.ts
playwrighte2e/pages/respClaimantDetails.ts
playwrighte2e/pages/respContactDetailsPages.ts
playwrighte2e/pages/respContestClaim.ts
playwrighte2e/pages/respSubmitEt3.ts
playwrighte2e/pages/respondentCaseOverviewPage.ts
playwrighte2e/pages/respondentTaskListPage.ts
playwrighte2e/pages/responseLandingPage.ts
playwrighte2e/tests/ET3Journey.test.ts
playwrighte2e/utils/config.ts
yarn.lock

Nightly dev

---

playwrighte2e/pages/caseTransferPage.ts
playwrighte2e/pages/et3LoginPage.ts
playwrighte2e/tests/ET3Journey.test.ts

fix CI failure

---

playwrighte2e/data/et-ccd-basic-data.json
playwrighte2e/pages/et3LoginPage.ts

Fix et3 test 27 1

---

playwrighte2e/pages/applicationTabPage.ts
playwrighte2e/tests/caseFileView.test.ts

https://tools.hmcts.net/jira/browse/RET-5572
This is a ticket to migrate CFV tests from Codeceptjs framework to Playwright

Ret 5572 - Migrate cfv tests to playwright

---

Jenkinsfile_nightly
playwrighte2e/steps/referralSteps.ts
playwrighte2e/tests/workAllocation.test.ts
playwrighte2e/utils/config.ts

add WA referral test

---

Jenkinsfile_nightly
playwrighte2e/steps/referralSteps.ts
playwrighte2e/tests/caseFlag.test.ts
playwrighte2e/tests/workAllocation.test.ts
playwrighte2e/utils/config.ts

Wa script 
remove skip tag from case flag

Wa add script

---

package.json

disable  accessibility test run on functional step

---

Jenkinsfile_nightly
package.json

https://tools.hmcts.net/jira/browse/RET-5099

Ret 5099 - Add smoke test to xui-e2e repo

---

playwrighte2e/pages/caseListPage.ts

fix referral tests

---

Jenkinsfile_nightly
package.json
playwrighte2e/tests/caseSubmission.test.ts
playwrighte2e/tests/claimantDetails.test.ts
playwrighte2e/tests/etEvents.test.ts
playwrighte2e/utils/config.ts

https://tools.hmcts.net/jira/browse/RET-5641

Add tags for ccd-callback UI tests

---

playwrighte2e/common/web.action.ts
playwrighte2e/fixtures/page.fixture.ts
playwrighte2e/pages/hearingDetailsPage.ts
playwrighte2e/pages/referralPage.ts
playwrighte2e/pages/rolesAndAccessPage.ts
playwrighte2e/pages/taskPage.ts
playwrighte2e/steps/createAndAcceptCase.ts
playwrighte2e/steps/referralSteps.ts
playwrighte2e/tests/ET3Processing.test.ts
playwrighte2e/tests/claimantDetails.test.ts
playwrighte2e/tests/depositOrder.test.ts
playwrighte2e/tests/etEvents.test.ts
playwrighte2e/tests/referral.test.ts
playwrighte2e/tests/respondentDetails.test.ts
playwrighte2e/tests/workAllocation.test.ts

Wa tests 5594, 5694

---

playwrighte2e/pages/manageOrgPage.ts

fix CI 30/4

---

playwrighte2e/tests/ET3RespondentcontactDetails.test.ts
playwrighte2e/tests/caseSubmission.test.ts

remove duplication

---

playwrighte2e/pages/basePage.ts
playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/uploadDocumentPage.ts
playwrighte2e/tests/ET3RespAndClaimantContactDetails.test.ts
playwrighte2e/tests/respondentApplications.test.ts

fix CI 20/05

---

playwrighte2e/tests/caseSubmission.test.ts

Re enable skipped test

---

playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/citizenHubPage.ts
playwrighte2e/pages/createCaseThroughApi.ts
playwrighte2e/utils/config.ts

See [RET-2421](https://tools.hmcts.net/jira/browse/RET-2421)
Add environment variables for COS preview API URLs so UI tests can be executed against Preview

Add environment variables for COS preview API URLs

---

playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/legalRepPage.ts
playwrighte2e/steps/bundleSteps.ts

fix CI tests

---

playwrighte2e/data/et-england-case-data-caseworker.json
playwrighte2e/data/et-scotland-case-data-caseworker.json
playwrighte2e/pages/caseListPage.ts
playwrighte2e/pages/createCaseThroughApi.ts
playwrighte2e/pages/respondentCaseOverviewPage.ts
playwrighte2e/steps/createAndAcceptCase.ts
playwrighte2e/tests/respondentStoreApplication.test.ts

RespondentApplication unrepresented tests
